feedstore/config/routes.rb
Feedstore::Application.routes.draw do
  devise_for :users

   resources :feeds do
     resources :comments
   end
   
  resources :feed_display
  
  match  "/rss/:tag" => "rss_feeds#generate_rss.rss"
  
  
  get 'feed_display' => 'feed_display#index'

  get "home/index"

  get "feed_collector/feed_collector"
  
  get "feed_collector/test_local_rss"
  
  post "/feed_collector/populate_feeds"
    
  get "/rss_feeds/generate_rss"
  
  

  
  
  root :to => "home#index"
  
end

feedstore/app/models/comment.rb
# Model to store comment in database
# A comment belongs to feed
class Comment < ActiveRecord::Base
  attr_accessible :body, :feed_id
  belongs_to :feed
  
  validates_presence_of :body
end

feedstore/app/controllers/comments_controller.rb
=begin
 This class represents the controller for the comments which 
 are shown in the view for the feed show operation. 
=end
class CommentsController < ApplicationController
  
  #We would need to perform devise based authentication to 
  #access this controller.
  before_filter :authenticate_user!
  
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all

    respond_to do |format|
      format.html # index.html.erb
      #format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      #format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
 def create
   
  @feed = Feed.find(params[:feed_id])
    @comment = @feed.comments.build(params[:comment])
    @comment.userid=current_user.email
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@feed, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @feed, :status => :created, :location => @feed }
      else
        format.html { redirect_to(@feed, :notice => 
        'Comment could not be saved. Please fill in all fields')}
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    @feed = @comment.feed
    
    respond_to do |format|
      #check if the user is authorized to make changes to the commment.
      #he is allowed to make changes if he created the comments. Otherwise
      #show the unauthorized page to him.
      unless is_authorized_user_for_comment()
        format.html  { render :file =>  "#{Rails.root}/public/422.html" }
      end
      
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@feed, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end
  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @feed = Feed.find(params[:feed_id])
    @comment.destroy

    respond_to do |format|
       #check if the user is authorized to make changes to the commment.
      #he is allowed to make changes if he created the comments. Otherwise
      #show the unauthorized page to him.
      unless is_authorized_user_for_comment()
        format.html  { render :file =>  "#{Rails.root}/public/422.html" }
      end
      
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@feed, :notice => 'Comment was successfully deleted.') }
        format.xml  { head :ok }
      end
    end
  end
  
  #This method is used to check if user who created the comment
  #is the same as the logged in user. This gives us authorization 
  #for update, destroy methods. It requires the comment to be set 
  #in the @comment member variable of the class.
  def is_authorized_user_for_comment
    return current_user.email == @comment.userid
  end
   
end

feedstore/app/helpers/comments_helper.rb
module CommentsHelper
end

feedstore/app/views/comments/_comment.html.erb
<% div_for comment do %>
  <p> 
  	<strong> Posted <%= time_ago_in_words(comment.created_at) %>
    ago </strong><br/>
    <%= h(comment.body) %> 		
 </p>
<% end %>

feedstore/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feed_id %><br />
    <%= f.number_field :feed_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

feedstore/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for([:feed, @comment]) do |f| %>
    <div >
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <p><%= f.submit %></p>
<% end %>

feedstore/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Feed</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.feed_id %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

feedstore/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

feedstore/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Feed:</b>
  <%= @comment.feed_id %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>