feedstore/config/routes.rb
Feedstore::Application.routes.draw do
  devise_for :users

   resources :feeds do
     resources :comments
   end
   
  resources :feed_display
  
  match  "/rss/:tag" => "rss_feeds#generate_rss.rss"
  
  
  get 'feed_display' => 'feed_display#index'

  get "home/index"

  get "feed_collector/feed_collector"
  
  get "feed_collector/test_local_rss"
  
  post "/feed_collector/populate_feeds"
    
  get "/rss_feeds/generate_rss"
  
  

  
  
  root :to => "home#index"
  
end

feedstore/app/models/feed.rb
# Model to represent the feed entry.
# This model contains 
#  name and url

class Feed < ActiveRecord::Base
  
  #The attributes that are accessible on the feeds db.
  attr_accessible :name,  :url, :userid
  
  has_many :comments , :dependent => :destroy
  has_many :tags , :dependent => :destroy 
 
  MIN_NAME_LENGTH = 2
  MAX_NAME_LENGTH = 25
   
  #All fields need to exist while inserting to the database.
  validates :name, :presence => true
  validates :url, :presence => true
  validates :userid, :presence => true
  
  #All the other validations required for each field.
  validates :name, :length => {  
    :minimum   => MIN_NAME_LENGTH,
    :maximum   => MAX_NAME_LENGTH,
    :too_short => "must have at least %{count} characters",
    :too_long  => "must have at most %{count} characters"
  }
  
  #Validate the URL for it being a valid URL in format
  validates :url, :uri => { :format => /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix }
  
  #Validate the URL for being a valid rss feed.
  validates :url, :rss => true
  
  validates_uniqueness_of :url
  validates_uniqueness_of :name
 
end

feedstore/app/controllers/feeds_controller.rb
require 'will_paginate'
#Controller for the page where feeds can be viewed and actions performed
class FeedsController < ApplicationController
  
  @url_vs_tagnames = Hash.new
  
  #We would need to perform devise based authentication to 
  #access this controller.
  before_filter :authenticate_user!
  
  private 
  def set_view_variables
    
    ap "In feeds controller set_view_variables"
    #Create the hashes here
    @url_vs_tagnames = Hash.new
    
    #Get all the unique tags in the tags table
    tags_list = Tag.all
    
    unless tags_list.nil?
      for tagitem in tags_list
        #Get the feed associated with the tag 
        feeditem = Feed.where("id = ?", tagitem.feed_id)
        
        url = feeditem.first.url;
        
        unless url.nil?
          #Put url in the map
          if @url_vs_tagnames[url].nil?
             @url_vs_tagnames[url] = tagitem.tagname
          else
             @url_vs_tagnames[url] = @url_vs_tagnames[url] + ', ' + tagitem.tagname
          end
        end
      end
    end
    
  end
  
  # GET /feeds
  # GET /feeds.json
  # This method fetches all the feeds for display
  public
  def index
    
    set_view_variables()
    
    # Displays feeds with pagination enabled- 10 Feeds are displayed
    # per page. Prev, Next buttons are provided if more than 10
    # feeds are present
    @feeds = Feed.paginate(:page => params[:page], :per_page => 10)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  # Get individual feed details for display
  def show
    
    set_view_variables()
    
    #Retrieve the feed to be shown
    @feed = Feed.find(params[:id])
    #@new_comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  # Create new feed and tags for display
  def new
    
    ap params
    
    @feed = Feed.new
    @tag = Tag.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @feed }
    end
  end

  # GET /feeds/1/edit
  # Fetch the feed and the associated tags for editing
  def edit
  
    
    @feed = Feed.find(params[:id])
    
    @tags = Tag.find_all_by_feed_id(@feed.id)
    

  end

  # The tags are seperated by comma. This method splits
  # the tags using comma as delimiter
  def split_comma_seperated_tags(tags_with_comma) 
      split_tags = Array.new
      unless tags_with_comma.nil?
        split_tags = tags_with_comma.split(',')
      end
      
      #Now trim each tag for spaces.
      ret_val = Array.new
      for tag in split_tags
        ret_val.push(tag.strip)
      end
      
      return ret_val
  end
  
  
  # POST /feeds
  # POST /feeds.json
  # Create the feed using the parameters passed from the view
  
  def create
  
    tags = params[:selection]
    
    tags_from_client = split_comma_seperated_tags(tags)
    
    @feed = Feed.new(params[:feed])
    @tags = Array.new
    for each_tag in tags_from_client
        atag = Tag.new
        atag.tagname = each_tag
        @tags << atag
    end
    
    feed  = params[:feed]
    
    url =  feed['url']
    
    
    # If url doesnt have http or https, then attach it
    # Rails inbuilt url validator expects url to start with either http
    # or https
    if url.length > 0
      unless url.match(/^http/)
          @feed.url = "http://"  + url
      end
    end
    
    if validate_tags(tags, @feed)
        
        respond_to do |format|
            format.html { render :action => "new" }
        end
    
    return
    
    end
    
    

    error = false
    begin
      
      
      Feed.transaction do
      
        
        @tags = Array.new
        for each_tag in tags_from_client
          atag = Tag.new
          atag.tagname = each_tag
          @tags << atag
        end
        
        @feed.tags = @tags
        ap @tags
        
        @feed.save!
        
      
    end
      
    rescue Exception => e
      error = true
    end   
       
    respond_to do |format|
      if error == false
        format.html { redirect_to @feed, :notice => 'Feed was successfully created.' }
        format.json { render :json => @feed, :status => :created, :location => @feed }
      else
        format.html { render :action => "new" }
        format.json { render :json => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def validate_tags(tags, feed) 
  
  error = false
  tags_from_client = Array.new
    begin
      tags_from_client = split_comma_seperated_tags(tags)
    rescue 
      error = true
      feed.errors.add("tag", "  not valid")
    end
    
    if tags_from_client.length == 0
          error = true
          feed.errors.add("tag", "cannot be empty")
    end
    for tag in tags_from_client
        if tag.length == 0
          error = true
          feed.errors.add("tag", " cannot be empty")
        end
    end


  return error
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  # Updates data for individual feed. Stores the feed 
  # and tags in the database
  def update
  
    @feed = Feed.find(params[:id])
    @tags = Tag.find_all_by_feed_id(@feed.id)
    
    tags = params[:selection]
    
    feed  = params[:feed]
    url =  feed['url']
    
    # If url doesnt have http or https, then attach it
    # Rails inbuilt url validator expects url to start with either http
    # or https
    if url.length > 0
      unless url.match(/^http/)
          @feed.url = "http://"  + url
      end
    end
    if validate_tags(tags, @feed)
        
        respond_to do |format|
            format.html { render :action => "edit" }
        end
    
    return
    
    end
    
    
    tags_from_client = split_comma_seperated_tags(tags)
    
    #Either save everything or dont. Atomic operations.
    @tags = Array.new
    
    Tag.transaction do
      
        Tag.destroy_all(:feed_id => @feed.id)
        
        #Save new tags in the database    
        for tag_name in tags_from_client
            @tag = Tag.new
            @tag.feed_id=@feed.id
            @tag.tagname=tag_name
            @tags << @tag
        end
      
    end
    @feed.tags = @tags
    
    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, :notice => 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  # Delete from database. Deletes both feed and the associated tags using 
  # the belongs_to and has_to association
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

feedstore/app/helpers/feeds_helper.rb
module FeedsHelper
end

feedstore/app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>

<% if @feed.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

	<ul>
		<% @feed.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<table>

	<tr>
		<td><label>Tag(s)</label></td>

		<td> 
			<% if @tags.nil? %>
				<input type="text" name="selection" id="selection" >
			<% else %>

				<% value = ""%>
				<% for tag in @tags %>
					<% value = value + tag.tagname + "," %>
				<% end %>
		
			<input type="text" name="selection" id="selection"  value=<%= value %> >
		
			<% end %> </td>
	</tr>

	<tr>
		<td> <%= f.label :name %> </td>
		<td> <%= f.text_field :name, :size => '90%' %> </td>
	</tr>

	<tr>
		<td> <%= f.label :url %> </td>
		<td> <%= f.text_field :url, :size => '90%' %> </td>
	</tr>

	<tr>
		<td> <%= f.label :userid %> </td>
		<td> <%= f.text_field :userid, :readonly => true, :value => current_user.email, :size => '90%'%> </td>
	</tr>
</table>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

feedstore/app/views/feeds/_header.html.erb
<% content_for :javascript_includes do %>
<%= javascript_include_tag "jquery.js" %>
<%= javascript_include_tag "jquery.layout.js" %>
<!-- <%= javascript_include_tag "jquery.ui.all.js" %> -->
<%= javascript_include_tag "jquery-ui.min.js" %>
<% end %>

<script type="text/javascript">
    $(document).ready(function() {
        $('body').layout({
            applyDemoStyles : true
        });
    }); 
</script>

<div class="header-left">
	Feed-Store, a community driven RSS-content aggregator
</div>

<div id="user_nav" >
	<% if user_signed_in? %>
	Signed in as <%= current_user.email %> | <%= link_to " Sign out ", destroy_user_session_path %>
	<% else %>
	<%= link_to " Sign up ", new_user_registration_path %>  or <%= link_to "sign in", new_user_session_path %>
	<% end %>
</div>

feedstore/app/views/feeds/_home.html.erb
<%= link_to "Go To Home Page", feed_display_index_path %>

feedstore/app/views/feeds/edit.html.erb
<div class="ui-layout-center">

	<h1>Editing feed</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @feed %> |
	<%= link_to 'Back', feeds_path %> |
	<%= render 'home' %>
</div>

<div class="ui-layout-north">
	<%= render 'header' %>

</div>

feedstore/app/views/feeds/index.html.erb
<div class="ui-layout-center">
	<h2>Listing feeds</h2>

	<div class="flickr_pagination">
		<div id="page_info">
			<table>
				<tr>
					<th>Tag</th>
					<th>Name</th>
					<th>Url</th>
					<th>Userid</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>

				<% @feeds.each do |feed| %>
				<tr>
					<td> <%= @url_vs_tagnames[feed.url] %> </td>
					<td><%= feed.name %></td>
					<td><%= link_to feed.url, feed.url, :target => '_blank' %></td>
					<td><%= feed.userid %></td>
					<td><%= link_to 'Show', feed %></td>
					<td><%= link_to 'Edit', edit_feed_path(feed) %></td>
					<td><%= link_to 'Destroy', feed, :method => :delete, :data => { :confirm => 'Are you sure you want to delete the entry in the table?' } %></td>
				</tr>
				<% end %>
			</table>
		</div>
		<br>
		<%= will_paginate @feeds %>
	</div>
	<br />

	<%= link_to 'New Feed', new_feed_path %> |
	<%= render 'home' %>

</div>
<div class="ui-layout-north">
	<%= render 'header' %>

</div>

feedstore/app/views/feeds/new.html.erb
<div class="ui-layout-center">

	<h1>New feed</h1>

	<%= render 'form' %>

	<%= link_to 'Back', feeds_path %> |
	<%= render 'home' %>

</div>

<div class="ui-layout-north">
	<%= render 'header' %>

</div>

feedstore/app/views/feeds/show.html.erb
<div class="ui-layout-center">

	<p id="notice">
		<%= notice %>
	</p>

	<div class="flickr_pagination">
		<div id="page_info">
			<table>
				<tr>
					<th> Tag </th>
					<th> Name </th>
					<th> URL </th>
					<th> UserID </th>
				</tr>

				<tr>
					<td> <%= @url_vs_tagnames[@feed.url] %> </td>
					<td> <%= @feed.name %> </td>
					<td> <%= link_to @feed.url, @feed.url, :target => "_blank" %> </td>
					<td> <%= @feed.userid %> </td>
				</tr>
			</table>
		</div>
	</div>

	<%= link_to 'Edit', edit_feed_path(@feed) %> |
	<%= link_to 'Back', feeds_path %> |
	<%= render 'home' %>

	<h2>Comments</h2>
	<div id='comments'>
		<%= render :partial => @feed.comments %>
	</div>

	<% @feed.comments.each do |comment| %>

	<div id="comment" >
		<%= h(comment.body) %> </br>
		[<i><%= comment.userid %> |
		Posted <%= time_ago_in_words(comment.created_at) %> ago</i>]
		<br/>
		<% if current_user.email==comment.userid %>
		<%= link_to_if(current_user.email==comment.userid,  'Edit', edit_feed_comment_path(@feed, comment) )%> |
		<%= link_to_if(current_user.email==comment.userid,  'Delete', feed_comment_path(@feed, comment), :confirm => 'Are you sure?', :method => :delete) %>
		<% end %>
	</div>
	<%end%>

	<%= form_for([@feed, @feed.comments.build]) do |f| %>

	<p>
		<%= f.label :body, "New Comment" %>
		<br/>
		<%= f.text_area :body , :rows=>10, :cols=>72 %>
	</p>
	<p>
		<%= f.submit "Add Comment" %>
	</p>
	<% end %>

</div>



<div class="ui-layout-north">
	<%= render 'header' %>

</div>